### ISSUE TITLE
Subscribe to client's state change notifications

### ISSUE THREAD

**Issue by jenyayel** [Enttoi/enttoi-ui-web#2]
I'm summarizing what is desired for the first phase of this feature

- [x] Once I notified , I should be auto-unsubscribed (from all clients?)
- [x] As first step, let's utilize plain old alert()
- [x] I'm not sure that localStorage is suitable. Because the subscriptions to notification is not long-term. Imagine that I subscribe to something, close browser, get back after few hours/days and then what? I should start from clean.
- [ ] Let me know what you think about this one: when I subscribe (or may be even for all clients) I can see the counter of people that already subscribed. This will get some kind of indication what are my chances for actually getting available cabin when I notified. This of course will require support on API.

**Comment by AmirSasson** [comment]
having an issue with when browser doesn't support Notification we show multiple alerts instead of one.
(even though we set the client as unsubscribed)

**Comment by jenyayel** [comment]
I noticed that you switched to toastr instead of alert. I think alert is better, becuase will bring to focus or at least blink a window when it is not in focus. Now, in order not to block the UI thread, you should do the following:
```javascript
setTimeout(() => alert('Not blocking'), 0);
```
