### ISSUE TITLE
Pre-subscribe to notification validations

### ISSUE THREAD

**Issue by jenyayel** [Enttoi/enttoi-ui-web#5]
- [x] I'm able to subscribe to the client that has one the cabins is 'FREE'. IMHO, should be prevented.
- [ ] I'm able to subscribe to female client after subscribing to male client. Not sure whether there is any sense in it. Even if yes, then should be unsubscribed from both female and male when on of them becomes available? Anyway, it is easier just to prevent it.

**Comment by jenyayel** [comment]
What we decided on second bullet? Won't fix?

**Comment by AmirSasson** [comment]
I am saying lets leave this option opened.
Not blocking from subscribing to different genders.
